### ISSUE TITLE
Latest release tag has a misleading typo

### ISSUE THREAD

**Issue by doz10us** [uilianries/conan-ldap-authentication#17]
The latest tag is `2.0.3` which I believe is a typo from `0.2.3`.
This is a bit misleading because:

1. It looks like plugin is now officially stable
2. It is different from versions available at `pip` (where `0.2.3` is the latest)

**Comment by uilianries** [comment]
Well observed, Thanks for report. I'll fix ASAP

**Comment by uilianries** [comment]
Done! Created release 0.2.3 and removed 2.0.3

Please, re-open this issue if you detect some problem.

Regards!
