### ISSUE TITLE
Is conan-ldap-authentication still alive?

### ISSUE THREAD

**Issue by je-vv** [uilianries/conan-ldap-authentication#18]
I wanted to enable conan_server ldap authentication through the conan recommended conan-ldap-authentication plugin, but I don't get the plugin to connect with the ldap server at all, I always get from the conan_server output:

> conan_server 
> ***********************
> Using config: /users/<username>/.conan_server/server.conf
> Storage: /ws/<username>/conan
> Public URL: https://localhost:9300/v1
> PORT: 9300
> ***********************
> Bottle v0.12.18 server starting up (using WSGIRefServer())...
> Listening on http://0.0.0.0:9300/
> Hit Ctrl-C to quit.
> 
> 127.0.0.1 - - [04/Jun/2020 13:18:36] "GET /v1/ping HTTP/1.0" 200 0
> WARNING:root:{'desc': "Can't contact LDAP server", 'errno': 107, 'info': 'Transport endpoint is not connected'}
> 127.0.0.1 - - [04/Jun/2020 13:18:36] "GET /v1/users/authenticate HTTP/1.0" 401 22

I was trying to figure out how the plugin set the certs to verify the ldap server certificates, and found nothing about it.  I noticed the plugin is based on pyldap, and indluces pyldap as a requirement, but looking at [pyldap-doc](https://pypi.org/project/pyldap), what one needs to use instead is python-ldap, hopefully >= 3.0.0.  Then I noticed no commits have happened to the plugin for quite a while.

So I'm wondering if this conan ldap authnticator is still alive, or if there's an alternative out there, or if one now a days one needs to write its own...

**Comment by uilianries** [comment]
Hi @je-vv !

I strong recommend you using [Artifactory](https://docs.conan.io/en/latest/uploading_packages/artifactory_ce.html) instead of conan-center. It's the spiritual successor of conan-center and offers more features, including [LDAP](https://www.jfrog.com/confluence/display/JFROG/LDAP) support.

I didn't commit any new change, because Artifactory covers all cases. Probably I'll archive this project.

**Comment by je-vv** [comment]
One quick question regarding artifactory CE, when I read the EULA, it stated it was fro personal use only, and I want to use the server for an organization within a company.  That's not all the reasoning behind preferring conan_server, but also command line control and such, but I was still intrigued by the EULA.

**Comment by je-vv** [comment]
BTW, I got it working, 1st, I had to make ldapsearch work authenticating (with the ldaps host), which required several certificates settings I was missing, and once I was able to normally authenticate against the ldaps server with ldapsearch, I just needed as config:
```
[ldap]
host: ldaps://ed.hpecorp.net
distinguished_name: uid=$username,ou=People,o=<company domain>
```
@uilianries, so the authenticator is still working with conan_server (and that without you last update on git), and it seems to me we'll prefer keep using conan_server.  So if you get a new release with your updates, that should be OK I'd guess.  How about the artifactory CE question I posted, do you know by any chance?

**Comment by uilianries** [comment]
> How about the artifactory CE question I posted, do you know by any chance?

Totally possible, you can use in your company, no problem.
